version: '3.9'

services:
  nginx:
    image: nginx:alpine
    container_name: mazik-alpen-nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d/:delegated
      - ./www:/var/www/html:delegated
    depends_on:
      - php
  php:
    image: php:fpm-alpine
    container_name: mazik-alpen-php
    volumes:
      - ./www:/var/www/html:delegated